### ISSUE TITLE
Fix the Team page

### ISSUE THREAD

**Issue by RahulGopathi** [devlup-labs/devlup-labs.github.io#55]
### **Current Behaviour**
Current Team page is blank and shows no one

### **Expected Behaviour**
Fix the Google sheets API error and display all the team profiles

**Comment by Amank-root** [comment]
Hi, @RahulGopathi can you please assign it to me?

**Comment by RahulGopathi** [comment]
Sure @Amank-root

**Comment by yuvrajrathva** [comment]
Fixed with PR #79, Credits: @kunxl-gg
