### ISSUE TITLE
Auto Deploy to GitHub pages

### ISSUE THREAD

**Issue by RahulGopathi** [devlup-labs/devlup-labs.github.io#65]
### **Current Behaviour**
We have to manually push to the `gh-deployments` branch to deploy the changes
### **Expected Behaviour**
Write a script and use GitHub Actions to deploy the changes whenever we push to the `vue` branch

**Comment by nkilm** [comment]
I would like to work on this issue, please assign me.

**Comment by RahulGopathi** [comment]
Sure go ahead! @nkilm

**Comment by RahulGopathi** [comment]
@nkilm Any Updates?

**Comment by nkilm** [comment]
@nkilm I'll get to it asap! Little busy with exams.

**Comment by kunxl-gg** [comment]
The PR:#85 fixes this. Credits @yuvrajrathva
