### ISSUE TITLE
API KEY is exposed⚠

### ISSUE THREAD

**Issue by nkilm** [devlup-labs/devlup-labs.github.io#66]
#### `.env` file is not added to .gitignore, it contains `VUE_API_KEY` which should not be exposed to public.

**Comment by ThPadelis** [comment]
I can fix this one. Could you assign this to me?

**Comment by nkilm** [comment]
This cannot be fixed as anybody can view the API KEY from previous commits. 
#### One way could be to generate new API KEY and add .env to .gitignore.

**Comment by ThPadelis** [comment]
You are right. But, one other solution is to completely remove this file from the src and from git history also. 

Indeed, is better to generate a new API key and update the .gitignore file.

**Comment by nkilm** [comment]
Yes that might work.

**Comment by RahulGopathi** [comment]
Sure! Go ahead @ThPadelis

**Comment by ThPadelis** [comment]
Can you give me access to this repo? I can't make PR for this one.

**Comment by RahulGopathi** [comment]
> Can you give me access to this repo? I can't make PR for this one.

Just push to your repo, you should be able to make a PR. 

Reference: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by ThPadelis** [comment]
It's not that simple. I used `git filter-branch` command. `git filter-branch` lets you rewrite git revision history by rewriting the branches, and applying custom filters on each revision.

**Comment by RahulGopathi** [comment]
What access do you need? and Why are you using this command in the first place.

**Comment by RahulGopathi** [comment]
There is no need to remove that API key, just remove the .env file. That API key has been revoked already. :)

**Comment by nkilm** [comment]
Fixed via #70
